name: 'Get version from git tags'
description: 'Calculate semantic version from git tags'

outputs:
  version:
    description: 'The calculated version from git tags'
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - id: get-version
      shell: bash
      run: |
        # Get latest tag
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")

        # Remove 'v' prefix if present
        version=${latest_tag#v}

        IFS='.' read -r -a VERSION_PARTS <<< "$version"
        BUILD_RUN=${{ github.run_number }}

        # Increment the patch version
        if [ ${#VERSION_PARTS[@]} -eq 3 ]; then
          version="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}.$BUILD_RUN"
        else
          echo "Error: Invalid version format. Expected 'x.y.z'."
          exit 1
        fi

        echo "version=${version}"

        echo "version=${version}" >> $GITHUB_OUTPUT
