name: Integration

on:
  push:
    branches:
      - 'feature/**'
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - uses: ./.github/workflows/actions/get-version-from-git

      - run: |
          #bash ./build.sh nxTargets
