name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - uses: ./.github/workflows/actions/get-version-from-git
        id: get-version

      - name: Build projects
        uses: ./.github/workflows/actions/build-projects
        with:
          version: ${{ steps.get-version.outputs.version }}

      - name: Run unit tests (headless)
        env:
          CI: 'true'
        run: |
          npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

