name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - name: Publish to npm
        if: github.ref == 'refs/heads/main' # Nur auf dem main-Branch
        run: |
          #bash ./build.sh nxTargets

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # NPM-Token aus GitHub Secrets
